AllCops:
  Exclude:
    - vendor/**
    - metadata.rb

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
StringLiterals:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
Style/FileName:
  Enabled: false
